### ISSUE TITLE
Black background Codeforces logo

### ISSUE THREAD

**Issue by nzec** [GaurangTandon/codeforces-darktheme#30]
I have some ideas:

- Inverting the image using CSS does work but the background is not 100% black so it looks a bit odd.
- Use something like MarvinJ to remove background: https://stackoverflow.com/a/47793175/7345209
- Remove the background manually by going through the image pixel by pixel (we'll need to save it as well otherwise it will make things extremely slow)
- Upload a transparent background image of Codeforces logo somewhere and use it in place of the one hosted by Codeforces (will require manually adding special event logos)
- Spam Codeforces blogs to make logo background transparent.

**Comment by GaurangTandon** [comment]
Hey Aditya, here's my response:

1. In general, I'd avoid messing the foreground colors in the logo since it may have trademark issues.
2. MarvinJ is nice, but it will mess up "CODE" in the logo (black text on a black background).
3. see 2
4. see 2, and also I am not regular enough to keep updating the logo :P
5. I need my contribution points :)

Another important point I'd like to bring up: different organizational pages have different logos. (Here's [one](https://codeforces.com/group/yny9prUF8z/blog) for example, but it's private) Moreover, certain other pages have special logos, like here's one of [Harbour space](https://codeforces.com/blog/entry/51208). Making any changes to the logo area of the webpage would require having to make special exceptions for all the other pages, and I currently do not see a way to do this properly.

I'd reiterate I'm open to more ideas though, but the current ideas seem infeasible.

PS: also see #24
