### ISSUE TITLE
dark theme is not working since evening on codeforces, kindly resolve (chrome browser)

### ISSUE THREAD

**Issue by govind-ik** [GaurangTandon/codeforces-darktheme#52]

**Comment by Sujansinhthakor** [comment]
same here

**Comment by longwatermelon** [comment]
Using tampermonkey legacy fixed it for me

**Comment by ljfp** [comment]
It seems that this script only works with Tampermonkey Legacy (MV2).

**Comment by GaurangTandon** [comment]
Hi all! Thanks for reporting this issue. It looks like the issue is due to Tampermonkey's latest update:

https://github.com/tampermonkey/tampermonkey/issues/2201

As a workaround, please install Tampermonkey beta version in which this issue is fixed. You can install it from here:

https://chromewebstore.google.com/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf

I sincerely regret the inconvenience. I am closing this issue report as the issue is with the external tool and a workaround is also available.
