### ISSUE TITLE
NOT working

### ISSUE THREAD

**Issue by mehul-v0** [GaurangTandon/codeforces-darktheme#54]
The codefores dark theme is not working after the latest update of the tapermonkey

**Comment by GaurangTandon** [comment]
Hi @Mehul-Raj-01 

Please install Tampermonkey beta version in which this issue is fixed. You can install it from here:

chromewebstore.google.com/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf

As discussed in our previous issue https://github.com/GaurangTandon/codeforces-darktheme/issues/52
